#!/usr/bin/env python3
"""
Analyze roulette numbers from archives for PRNG patterns.
If numbers are generated by PHP mt_rand(), we may be able to
recover the seed and predict future numbers.
"""
import re
from collections import Counter

def parse_archive(filepath):
    """Parse roulette archive file, return list of (game_id, datetime, number)."""
    numbers = []
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        for line in f:
            line = line.strip()
            if line.startswith('===') or not line:
                continue
            # Format: 105890716 2026-01-01 00:00 - 30
            m = re.match(r'(\d+)\s+(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2})\s+-\s+(\d+)', line)
            if m:
                gid = int(m.group(1))
                dt = m.group(2)
                num = int(m.group(3))
                numbers.append((gid, dt, num))
    return numbers

# Parse all archives
archives = [
    '/root/heroeswm.ru/roul_archives/extracted/2026_01_roul.txt',
    '/root/heroeswm.ru/roul_archives/extracted/2026_02_roul.txt',
    '/root/heroeswm.ru/roul_archives/extracted/2026_03_roul.txt',
]

all_numbers = []
for path in archives:
    nums = parse_archive(path)
    print(f"{path.split('/')[-1]}: {len(nums)} numbers")
    all_numbers.extend(nums)

print(f"\nTotal numbers: {len(all_numbers)}")

# Check number range
values = [n[2] for n in all_numbers]
print(f"Min: {min(values)}, Max: {max(values)}")
print(f"Unique values: {sorted(set(values))}")

# Check if 00 is represented as 37 or something else
# American roulette: 0, 00, 1-36 = 38 numbers
# In the data, we see 0-36. Is 00 represented as 37?
if max(values) <= 36:
    print("NOTE: Max is 36 - 00 might be represented as 0, or missing, or as 37")
    print("Checking if 0 appears (could be both 0 and 00)...")
    
# Frequency analysis
freq = Counter(values)
print(f"\nFrequency analysis (top 10):")
for num, count in freq.most_common(10):
    expected = len(values) / 38
    print(f"  {num:3d}: {count:4d} times ({count/len(values)*100:.2f}%) expected {expected/len(values)*100:.2f}%")

print(f"\nFrequency analysis (bottom 10):")
for num, count in freq.most_common()[-10:]:
    print(f"  {num:3d}: {count:4d} times ({count/len(values)*100:.2f}%)")

# Check for 00 representation
print(f"\nDoes 37 appear? {37 in values}")
print(f"Does 38 appear? {38 in values}")

# Check sequential patterns
print("\n=== Sequential pattern analysis ===")
# Check if consecutive numbers have a pattern
diffs = [values[i+1] - values[i] for i in range(len(values)-1)]
diff_counter = Counter(diffs)
print(f"Most common consecutive differences:")
for d, c in diff_counter.most_common(10):
    print(f"  diff={d:+3d}: {c} times")

# Check if numbers follow mt_rand() pattern
# PHP mt_rand() generates 32-bit integers
# mt_rand(0, 37) would map to 0-37
# If 00 = 37, then we have 38 possible values (0-37)

# Check for period patterns
print("\n=== Period analysis ===")
# Check if there's a repeating pattern every N spins
for period in [38, 76, 114, 624, 8928]:
    if len(values) > period * 2:
        matches = sum(1 for i in range(period, len(values)) if values[i] == values[i-period])
        total = len(values) - period
        print(f"  Period {period}: {matches}/{total} matches ({matches/total*100:.1f}%)")

# Extract the hash at the end of each file
print("\n=== Hash analysis ===")
for path in archives:
    with open(path, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    hash_match = re.search(r'={3,}\s*([0-9a-f]+)', content)
    if hash_match:
        h = hash_match.group(1)
        print(f"  {path.split('/')[-1]}: hash = {h[:64]}...")
        print(f"    Length: {len(h)} hex chars = {len(h)*4} bits")

# Save numbers in format for php_mt_seed
# php_mt_seed expects: mt_rand(min, max) outputs
# Format: min max value min max value ...
print("\n=== Saving for seed cracking ===")
# If 00 is represented as 0, then range is 0-36 (37 values)
# If 00 is 37, then range is 0-37 (38 values)
# Let's check: does 0 appear unusually often?
zero_count = freq.get(0, 0)
print(f"  0 appears {zero_count} times (expected ~{len(values)/38:.0f} for 38-slot, ~{len(values)/37:.0f} for 37-slot)")

# Save in php_mt_seed format (assuming range 0-37 with 00=37)
# Actually, let's check if 00 is a separate entry
# In American roulette, 0 and 00 are different
# Let's check the data more carefully
print(f"\n  All unique values: {sorted(set(values))}")
print(f"  Count of unique: {len(set(values))}")

# If there are only 37 unique values (0-36), then 00 might be mapped to 0
# If there are 38 unique values (0-37), then 37 = 00

# Save for seed cracking
with open('/root/heroeswm.ru/roul_numbers.txt', 'w') as f:
    for v in values:
        f.write(f"0 37 {v}\n")  # mt_rand(0, 37) format
print(f"\n  Saved {len(values)} numbers to roul_numbers.txt for seed cracking")
print(f"  Format: min max value (for php_mt_seed)")
