package soul.utils
{
   import flash.net.registerClassAlias;
   import soul.model.TypedParam;
   import soul.model.ability.Ability;
   import soul.model.ability.actions.AbilityAction;
   import soul.model.ability.actions.AllyTargetBlinkAction;
   import soul.model.ability.actions.BlinkAction;
   import soul.model.ability.actions.BuffAction;
   import soul.model.ability.actions.BuffRemoveByGroupAction;
   import soul.model.ability.actions.BuffRemoveByIdAction;
   import soul.model.ability.actions.CasterExplodeAction;
   import soul.model.ability.actions.DamageAction;
   import soul.model.ability.actions.EnemyTargetBlinkAction;
   import soul.model.ability.actions.ExplodeAction;
   import soul.model.ability.actions.HealAction;
   import soul.model.ability.actions.PercentDamageAction;
   import soul.model.ability.actions.PercentHealAction;
   import soul.model.ability.actions.RandomBlinkAction;
   import soul.model.ability.actions.SummonAction;
   import soul.model.ability.actions.TargetBlinkAction;
   import soul.model.ability.actions.TargetExplodeAction;
   import soul.model.ability.actions.UnitAbilityAction;
   import soul.model.ability.actions.UnitExplodeAction;
   import soul.model.ability.actions.VampirismAction;
   import soul.model.achievement.Achievement;
   import soul.model.achievement.AchievementGroup;
   import soul.model.achievement.AchievementSubgroup;
   import soul.model.astral.AstralCircle;
   import soul.model.astral.AstralData;
   import soul.model.astral.AstralMember;
   import soul.model.astral.CitadelInfo;
   import soul.model.avatar.Avatar;
   import soul.model.buff.Aura;
   import soul.model.buff.Effect;
   import soul.model.buff.effects.BuffEffect;
   import soul.model.buff.effects.BuffGroupImmunityEffect;
   import soul.model.buff.effects.BuffGroupSet;
   import soul.model.buff.effects.ElementImmunityEffect;
   import soul.model.buff.effects.ParamEffect;
   import soul.model.buff.effects.PropertyEffect;
   import soul.model.buff.effects.ShieldEffect;
   import soul.model.character.CharInfoData;
   import soul.model.character.CharacterData;
   import soul.model.character.CharacterPublicData;
   import soul.model.character.InstanceRecord;
   import soul.model.character.ParamBonus;
   import soul.model.character.Reputation;
   import soul.model.chat.ChatMessage;
   import soul.model.chat.ChatTabData;
   import soul.model.chat.ChatUser;
   import soul.model.chat.ClientMessage;
   import soul.model.chat.Message;
   import soul.model.chat.SystemMessage;
   import soul.model.combat.AbilityApplyRecord;
   import soul.model.combat.BuffGroupImmunityRecord;
   import soul.model.combat.CombatRecord;
   import soul.model.combat.DamageRecord;
   import soul.model.combat.EffectApplyRecord;
   import soul.model.combat.EffectDispelRecord;
   import soul.model.combat.EffectExpireRecord;
   import soul.model.combat.ElementImmunityRecord;
   import soul.model.combat.ExperienceRecord;
   import soul.model.combat.HealRecord;
   import soul.model.combat.KillRecord;
   import soul.model.combat.MissRecord;
   import soul.model.combat.NamedCombatRecord;
   import soul.model.combat.StatusRecord;
   import soul.model.common.ShortMessage;
   import soul.model.condition.Condition;
   import soul.model.cooldown.Cooldown;
   import soul.model.cooldown.CooldownData;
   import soul.model.field.BaseUnit;
   import soul.model.field.FieldData;
   import soul.model.field.FieldUnit;
   import soul.model.field.mapconfig.ContourPoint;
   import soul.model.field.mapconfig.MapBackground;
   import soul.model.field.mapconfig.MapConfig;
   import soul.model.field.mapconfig.MapData;
   import soul.model.field.mapconfig.MapFillZone;
   import soul.model.field.mapconfig.MapLayer;
   import soul.model.field.mapconfig.MapLayout;
   import soul.model.field.mapconfig.MapLight;
   import soul.model.field.mapconfig.MapLights;
   import soul.model.field.mapconfig.ObjectConfig;
   import soul.model.field.mapconfig.TriggerZoneConfig;
   import soul.model.field.spriteconfig.ObjectLayout;
   import soul.model.field.spriteconfig.SpriteConfig;
   import soul.model.field.spriteconfig.SpritePhase;
   import soul.model.field.spriteconfig.SpritePoint;
   import soul.model.field.spriteconfig.SpriteZone;
   import soul.model.group.GroupData;
   import soul.model.group.GroupMember;
   import soul.model.interaction.arena.ArenaData;
   import soul.model.interaction.arena.ArenaStateData;
   import soul.model.interaction.auction.AuctionConfig;
   import soul.model.interaction.auction.AuctionData;
   import soul.model.interaction.auction.AuctionFilter;
   import soul.model.interaction.auction.Lot;
   import soul.model.interaction.auction.LotData;
   import soul.model.interaction.auction.LotTime;
   import soul.model.interaction.barter.BarterData;
   import soul.model.interaction.clan.ClanBonus;
   import soul.model.interaction.clan.ClanCreationData;
   import soul.model.interaction.clan.ClanData;
   import soul.model.interaction.clan.ClanInfo;
   import soul.model.interaction.clan.ClanMember;
   import soul.model.interaction.clan.ClanRecord;
   import soul.model.interaction.clan.ClanRole;
   import soul.model.interaction.clan.ClanSack;
   import soul.model.interaction.craft.Component;
   import soul.model.interaction.craft.CraftData;
   import soul.model.interaction.craft.Recipe;
   import soul.model.interaction.dashboard.BattlegroundEntry;
   import soul.model.interaction.dashboard.BattlegroundStatistics;
   import soul.model.interaction.dashboard.CitadelEntry;
   import soul.model.interaction.dashboard.Combatant;
   import soul.model.interaction.dashboard.DashboardEntry;
   import soul.model.interaction.dashboard.Team;
   import soul.model.interaction.dialog.DialogAnswer;
   import soul.model.interaction.dialog.DialogBranch;
   import soul.model.interaction.dialog.MetaItem;
   import soul.model.interaction.lfg.GroupApplication;
   import soul.model.interaction.lfg.LFGCriteria;
   import soul.model.interaction.lfg.LFGData;
   import soul.model.interaction.lfg.LFGUser;
   import soul.model.interaction.lfg.QuestCriteria;
   import soul.model.interaction.lfg.SectorCriteria;
   import soul.model.interaction.loot.LootItem;
   import soul.model.interaction.mail.Mail;
   import soul.model.interaction.mail.MailData;
   import soul.model.interaction.map.SectorData;
   import soul.model.interaction.quest.HintEntry;
   import soul.model.interaction.quest.QuestDetail;
   import soul.model.interaction.quest.QuestEntry;
   import soul.model.interaction.resurrection.ResurrectionData;
   import soul.model.interaction.resurrection.ResurrectionItemOption;
   import soul.model.interaction.resurrection.ResurrectionMoneyOption;
   import soul.model.interaction.ruby.Subscription;
   import soul.model.interaction.social.SocialElement;
   import soul.model.inventory.InventoryData;
   import soul.model.item.AbilityPatch;
   import soul.model.item.InvKey;
   import soul.model.item.Item;
   import soul.model.item.ItemAutoAbility;
   import soul.model.item.ItemInfoData;
   import soul.model.item.ItemShortcut;
   import soul.model.item.SetInfo;
   import soul.model.location.academy.AcademyData;
   import soul.model.location.academy.AcademyOptionData;
   import soul.model.location.shop.SellData;
   import soul.model.location.shop.ShopData;
   import soul.model.location.shop.ShopItem;
   import soul.model.location.temple.AbilityCast;
   import soul.model.location.temple.HealData;
   import soul.model.location.workshop.WorkshopItem;
   import soul.model.system.GameCfg;
   import soul.model.talents.Talent;
   import soul.model.talents.TalentData;
   import soul.model.talents.TalentRankDetail;
   import soul.model.talents.TalentRequirement;
   import soul.view.rtm.PanelShortcut;
   
   public class RemoteClassRegister
   {
      
      private static const classMap:Object = {};
      
      classMap["Ability"] = Ability;
      classMap["AbilityCast"] = AbilityCast;
      classMap["AcademyData"] = AcademyData;
      classMap["AcademyOptionData"] = AcademyOptionData;
      classMap["ArenaData"] = ArenaData;
      classMap["ArenaStateData"] = ArenaStateData;
      classMap["AstralCircle"] = AstralCircle;
      classMap["AstralData"] = AstralData;
      classMap["AstralMember"] = AstralMember;
      classMap["AuctionConfig"] = AuctionConfig;
      classMap["AuctionData"] = AuctionData;
      classMap["AuctionFilter"] = AuctionFilter;
      classMap["Aura"] = Aura;
      classMap["Avatar"] = Avatar;
      classMap["BarterData"] = BarterData;
      classMap["BaseUnit"] = BaseUnit;
      classMap["BattlegroundEntryData"] = BattlegroundEntry;
      classMap["CharacterData"] = CharacterData;
      classMap["CharacterPublicData"] = CharacterPublicData;
      classMap["CharInfoData"] = CharInfoData;
      classMap["ChatMessage"] = ChatMessage;
      classMap["ChatTabData"] = ChatTabData;
      classMap["ChatUser"] = ChatUser;
      classMap["CitadelEntryData"] = CitadelEntry;
      classMap["CitadelInfo"] = CitadelInfo;
      classMap["ClanBonus"] = ClanBonus;
      classMap["ClanCreationData"] = ClanCreationData;
      classMap["ClanData"] = ClanData;
      classMap["ClanInfo"] = ClanInfo;
      classMap["ClanMember"] = ClanMember;
      classMap["ClanRecord"] = ClanRecord;
      classMap["ClanRole"] = ClanRole;
      classMap["ClanSack"] = ClanSack;
      classMap["ClientMessage"] = ClientMessage;
      classMap["QuestCondition"] = Condition;
      classMap["Cooldown"] = Cooldown;
      classMap["CooldownData"] = CooldownData;
      classMap["DashboardEntryData"] = DashboardEntry;
      classMap["DialogAnswer"] = DialogAnswer;
      classMap["DialogBranch"] = DialogBranch;
      classMap["EffectData"] = Effect;
      classMap["FieldUnit"] = FieldUnit;
      classMap["FieldData"] = FieldData;
      classMap["GameCfg"] = GameCfg;
      classMap["GroupData"] = GroupData;
      classMap["GroupMember"] = GroupMember;
      classMap["HealData"] = HealData;
      classMap["HintEntry"] = HintEntry;
      classMap["InvKey"] = InvKey;
      classMap["InstanceRecord"] = InstanceRecord;
      classMap["InventoryData"] = InventoryData;
      classMap["Item"] = Item;
      classMap["ItemAutoAbility"] = ItemAutoAbility;
      classMap["ItemInfoData"] = ItemInfoData;
      classMap["AbilityPatchData"] = AbilityPatch;
      classMap["ItemShortcut"] = ItemShortcut;
      classMap["LootItem"] = LootItem;
      classMap["Lot"] = Lot;
      classMap["LotData"] = LotData;
      classMap["LotTime"] = LotTime;
      classMap["Mail"] = Mail;
      classMap["MailData"] = MailData;
      classMap["MapBackgroundCfg"] = MapBackground;
      classMap["MapConfig"] = MapConfig;
      classMap["MapData"] = MapData;
      classMap["MapFillZoneCfg"] = MapFillZone;
      classMap["MapLayerCfg"] = MapLayer;
      classMap["MapLayoutCfg"] = MapLayout;
      classMap["MapLight"] = MapLight;
      classMap["MapLights"] = MapLights;
      classMap["Message"] = Message;
      classMap["MetaItem"] = MetaItem;
      classMap["ObjectCfg"] = ObjectConfig;
      classMap["ObjectLayoutCfg"] = ObjectLayout;
      classMap["ParamBonus"] = ParamBonus;
      classMap["QuestDetail"] = QuestDetail;
      classMap["QuestEntry"] = QuestEntry;
      classMap["QuickSlotShortcut"] = PanelShortcut;
      classMap["Reputation"] = Reputation;
      classMap["ResurrectionData"] = ResurrectionData;
      classMap["ResurrectionItemOption"] = ResurrectionItemOption;
      classMap["ResurrectionMoneyOption"] = ResurrectionMoneyOption;
      classMap["SectorData"] = SectorData;
      classMap["SellData"] = SellData;
      classMap["SetInfoData"] = SetInfo;
      classMap["ShopData"] = ShopData;
      classMap["ShopItem"] = ShopItem;
      classMap["ShortMessage"] = ShortMessage;
      classMap["SocialElement"] = SocialElement;
      classMap["SpriteCfg"] = SpriteConfig;
      classMap["SpritePhaseCfg"] = SpritePhase;
      classMap["PointCfg"] = SpritePoint;
      classMap["ContourPointCfg"] = ContourPoint;
      classMap["ZoneCfg"] = SpriteZone;
      classMap["Subscription"] = Subscription;
      classMap["SystemMessage"] = SystemMessage;
      classMap["Talent"] = Talent;
      classMap["TalentData"] = TalentData;
      classMap["TalentRankDetail"] = TalentRankDetail;
      classMap["TalentRequirement"] = TalentRequirement;
      classMap["TriggerZoneConfig"] = TriggerZoneConfig;
      classMap["TypedParam"] = TypedParam;
      classMap["WorkshopItem"] = WorkshopItem;
      classMap["BuffEffect"] = BuffEffect;
      classMap["ParamEffect"] = ParamEffect;
      classMap["PropertyEffect"] = PropertyEffect;
      classMap["ShieldEffect"] = ShieldEffect;
      classMap["ElementImmunityEffect"] = ElementImmunityEffect;
      classMap["BuffGroupImmunityEffect"] = BuffGroupImmunityEffect;
      classMap["BuffGroupSet"] = BuffGroupSet;
      classMap["AbilityAction"] = AbilityAction;
      classMap["BlinkAction"] = BlinkAction;
      classMap["BuffAction"] = BuffAction;
      classMap["BuffRemoveByGroupAction"] = BuffRemoveByGroupAction;
      classMap["BuffRemoveByIdAction"] = BuffRemoveByIdAction;
      classMap["UnitExplodeAction"] = UnitExplodeAction;
      classMap["CasterExplodeAction"] = CasterExplodeAction;
      classMap["TargetExplodeAction"] = TargetExplodeAction;
      classMap["DamageAction"] = DamageAction;
      classMap["ExplodeAction"] = ExplodeAction;
      classMap["HealAction"] = HealAction;
      classMap["RandomBlinkAction"] = RandomBlinkAction;
      classMap["SummonAction"] = SummonAction;
      classMap["UnitAbilityAction"] = UnitAbilityAction;
      classMap["VampirismAction"] = VampirismAction;
      classMap["PercentHealAction"] = PercentHealAction;
      classMap["PercentDamageAction"] = PercentDamageAction;
      classMap["TargetBlinkAction"] = TargetBlinkAction;
      classMap["AllyTargetBlinkAction"] = AllyTargetBlinkAction;
      classMap["EnemyTargetBlinkAction"] = EnemyTargetBlinkAction;
      classMap["AchievementGroup"] = AchievementGroup;
      classMap["AchievementSubgroup"] = AchievementSubgroup;
      classMap["Achievement"] = Achievement;
      classMap["AbilityApplyRecord"] = AbilityApplyRecord;
      classMap["CombatRecord"] = CombatRecord;
      classMap["StatusRecord"] = StatusRecord;
      classMap["DamageRecord"] = DamageRecord;
      classMap["EffectApplyRecord"] = EffectApplyRecord;
      classMap["EffectDispelRecord"] = EffectDispelRecord;
      classMap["EffectExpireRecord"] = EffectExpireRecord;
      classMap["ExperienceRecord"] = ExperienceRecord;
      classMap["HealRecord"] = HealRecord;
      classMap["KillRecord"] = KillRecord;
      classMap["MissRecord"] = MissRecord;
      classMap["NamedCombatRecord"] = NamedCombatRecord;
      classMap["BuffGroupImmunityRecord"] = BuffGroupImmunityRecord;
      classMap["ElementImmunityRecord"] = ElementImmunityRecord;
      classMap["LFGData"] = LFGData;
      classMap["GroupApplication"] = GroupApplication;
      classMap["LFGCriteria"] = LFGCriteria;
      classMap["QuestCriteria"] = QuestCriteria;
      classMap["SectorCriteria"] = SectorCriteria;
      classMap["LFGUser"] = LFGUser;
      classMap["BattlegroundStatistics"] = BattlegroundStatistics;
      classMap["Team"] = Team;
      classMap["Combatant"] = Combatant;
      classMap["CraftData"] = CraftData;
      classMap["Recipe"] = Recipe;
      classMap["Component"] = Component;
      
      public function RemoteClassRegister()
      {
         super();
      }
      
      public static function register() : void
      {
         var remoteClass:String = null;
         var klass:Class = null;
         for(remoteClass in classMap)
         {
            klass = classMap[remoteClass];
            try
            {
               registerClassAlias(remoteClass,klass);
            }
            catch(e:Error)
            {
            }
         }
      }
   }
}

